SERVER_NAME: localhost:3131
# Connection example
DATABASE: mongodb+srv://user-21:qweasd123@cluster0.n9prx.mongodb.net/pysvcdb?retryWrites=true&w=majority
REDIS: redis://HattF54CVZBH1mXhaQb90d@localhost:6379/0
MAX_ROW: 25
# End example
UPLOAD_FOLDER: ./uploads
MAX_CONTENT_LENGTH: 104857600
AUTH:
  SECRET:
    PRIVATE_KEY: ./../secrets/jwtRS256.key
    PUBLIC_KEY: ./../secrets/jwtRS256.pub
  JWT:
    AUD: https://api.jun26solution.com
    EXP: 43200
    HEADERS:
      ALG: RS256
      TYP: JWT
    ISS: auth_service
  SESSION: 300
LOG_LEVEL: DEBUG
LOG_PATH: ./logs
DATA_SERVICE: http://localhost:3132
API_VERSION: 1.0.0
